name: Deploy static content to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:


permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    container:
      image: alpine:latest

    steps:
      - name: Install Hugo, Git, and the worst version of Tar
        run: |
          apk update
          apk add hugo git tar

      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: 'true'
        # ref: 'www'

      - name: Configure Git safe.directory
        run: |
          git config --global --add safe.directory "${GITHUB_WORKSPACE}"

      - name: Update git submodules
        run: |
          cd ./themes/quixotist
          git fetch origin
          git reset --hard origin/master

      - name: Generate the site
        run: |
          rm -rf ./pub
          tree
          hugo --enableGitInfo

          # Prepare git to commit changes
          git config user.name '[CI]'
          git config user.email 'action@github.com'
          
          # Commit changes
          git add ./themes/quixotist ./.gitmodules
          git commit -m "sync ./themes/quixotist" || echo "Nothing to commit"
          git push origin HEAD || echo "Push failed; check repository settings"

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./pub"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
